### ISSUE TITLE
Cache inconsistent in `CachedStringRepository`

### ISSUE THREAD

**Issue by adherencegoo** [B3nedikt/restring#103]
Hi there
It's me again 🤣

When integrating this lib, I found issues, not sure if you are on purpose for these
1. Why are `afterPutAll` and `afterRemove` ignored? Shouldn't they be synced with `persistentMap`?
2. Why is `_supportedLocales` only updated in `afterPut`? How about `afterPutAll`, `afterRemove`, `afterClear`?
https://github.com/B3nedikt/restring/blob/c6a118b8eb9d1295cb2f8d6fe005df679bc9e7e8/restring/src/main/java/dev/b3nedikt/restring/repository/CachedStringRepository.kt#L30-L38

---
**Some experiments**

If adding the code
```
stringRepository.strings.remove(Locale.ENGLISH)
stringRepository.supportedLocales shouldContainSame setOf(Locale.FRENCH)
```

to these 2 test cases
https://github.com/B3nedikt/restring/blob/c6a118b8eb9d1295cb2f8d6fe005df679bc9e7e8/restring/src/test/java/dev/b3nedikt/restring/repository/SharedPrefStringRepositoryTest.kt#L31-L39
https://github.com/B3nedikt/restring/blob/c6a118b8eb9d1295cb2f8d6fe005df679bc9e7e8/restring/src/test/java/dev/b3nedikt/restring/repository/MemoryStringRepositoryTest.kt#L21-L29

then, `SharedPrefStringRepositoryTest` will fail, and `MemoryStringRepositoryTest` will succeed

**Comment by B3nedikt** [comment]
Hello again :) This was indeed a small bug I just fixed it with Restring 5.2.0. It contains a lot of small optimizations accumulated over the last year, including a method to create a Resources instance:
```kotlin
class ExampleApplication : Application() {

...

    override fun getResources(): Resources {
        return Restring.wrapResources(applicationContext, super.getResources())
    }
}
```
I still would not recommend using the application context to retrieve strings, due to potential issues with configuration changes, but it should be fine if you know what you are doing ;)
