### ISSUE TITLE
How do we support dynamic locales?

### ISSUE THREAD

**Issue by rhlmshr** [B3nedikt/restring#41]
Hello B3nedikt,

In my scenario, I have the following use case:

- Get the list of supported languages from API and show it to the user.
- The user selects any language.
- Take the locale of that language and convert all the string stored (currently in English only) to a JSON and get the translated string JSON from the backend.
- Inject these strings to each activity and fragment.

My issue with the implementation is I have to list out the type of locales that I support in Application. If it is all dynamic, how do I manage that? Also is there any way to extract the physical strings.xml file so that I can convert it to JSON for translation?

Thanks in advance.

**Comment by edgar-zigis** [comment]
I think you slightly misunderstand how this library should be used. strings.xml should be used only as a fallback if the app calls string identifier and your dynamic string loader has no such string. 

You definitely can preload supported locales but keep in mind, that you need to make sure that activities will be called only after the locales will be loaded. It can be achieved through the waiting in some splash screen activity or something like that. Probably it will mess up the first startup, but for the next launches you can save the locales in shared preferences and next time start the app without delay.

**Comment by B3nedikt** [comment]
Sounds like an interesting use case, I guess the reason why you why you want to convert all the strings to a JSON and not just the string names, is because you want to machine translate them on the backend?
If you have control over the backend I would recommend to store the strings also in the backend and only upload the string names of course.

As @edgar-zigis wrote you actually don't have to list all the locales you support in the Application. You can just set your strings anytime like this: 
```kotlin
Restring.setStrings(locale, newStrings);
```
Actually I will deprecate the StringsLoader in version 5 of restring because it is a misleading API & uses the deprecated AsyncTask internally. I would recommend to no longer use it. Restring does not care to which language you set your app too, it is the clients responsibility to make sure you set the language to one where strings are available. If there are no strings available restring will quietly fall back to your default strings.xml. My library "AppLocale" makes this easier, please have a look at this repositories sample app, to see how you can integrate it into your app. 

Yes, you can extract the strings.xml with a bit of reflection magic:
```kotlin
val fields = R.string::class.java.fields
val stringNames = fields.map { it.name }
```
You can now just get the string values the normal way with context.getString(...).

Does this help you?

**Comment by rhlmshr** [comment]
Hello B3nedikt and edgar-zigis,

Thanks, for the quick response. Something that I should learn from you. 

Currently, I am underdevelopment with the functionality you mentioned. That's why I couldn't get back to you as I was hoping to reply as soon as I am done with the functionality. Today, I am starting with the Android part. 

Yes, B3nedikt. Your interpretation is right we will be processing the strings on the backend. I have suggested the idea of putting the keys of string.xml on the backend but the client wants to be on the device end only. But we do have a caching mechanism in place at both App and Backend so it shouldn't pose much of the problem.

Regards

P.s. That string reflection trick was a lifesaver. There is just one glitch. Some of the string key value is marked translatable=false in strings.xml file. Is there any way to exclude them?

**Comment by B3nedikt** [comment]
You're welcome :)
The translatable=false is only a hint for the linter, you cannot check it at runtime. So you need a workaround here, e.g. making the translatable part of the string name.
