### ISSUE TITLE
Not updating strings for textviews in activity

### ISSUE THREAD

**Issue by ashu5398** [B3nedikt/restring#59]
When I am trying to put the textview in activity_main.xml layout and trying to update it, then it is not getting updated(String is being set to textview in xml). While the thing is working fine when I am using dataBinding with it. I have tried to regenerate the issue in your example only with a fork. You can test it on [this fork](https://github.com/ashu5398/restring) . Can you please help me fix this issue. 

**Note : I don't want to use ViewPump in my project.**

**Comment by B3nedikt** [comment]
While you can use Restring without ViewPump, there are actually a few limitations:

- You need to recreate the activity for UI changes in your XML layouts whenever you change your app language or update the Restring.stringRepository to take effect. To do this without recreating the activity Reword is needed, which depends on ViewPump
- You cannot directly updated any strings set from string resources in XML. 

While tricks with databinding like in your fork may work, this is outside of the scope of this library.

However I understand that you don't want to introduce ViewPump in your project. It is a rather verbose library that introduces some overhead as well as only working with very specific versions of appcompat depending on which version of ViewPump you use. That does lead to some maintenance issues and does add complexity ;)

I am actually working on a more lightweight alternative to ViewPump, which will be more tied to appcompat, but less dependent on specific versions of it. This will lead to about half the amount of code to do the same thing ViewPump does I hope :) Due to lot of other stuff I am working on no release plan for now though ;)

If you find a good workaround for your issue feel free to post it here, and I will add it to the Readme. I think other people may look for ways to get around using ViewPump as well, especially when you don't need updates without activity restarts anyway .

**Comment by ashu5398** [comment]
Recreating activity also does not work here, Even after recreating activity strings are not updating.

**Comment by ashu5398** [comment]
or if I use viewpump is it possible to make a fork of this library and use the viewpump just inside that library so that the complexity don't go for main module?

**Comment by B3nedikt** [comment]
> Recreating activity also does not work here, Even after recreating activity strings are not updating.

To be precise only the strings set statically in XML don't get updated. Every other string, e.g if fetched with getString() gets updated after a activity restart! As I have written above "You cannot directly updated any strings set from string resources in XML."

The technical reason for this is actually simpel: Restring works by using a custom Resources instance, which does get injected into the activity on every onCreate(), which is triggered by restarting the activity. String XML resources are wrapped in an AttributeSet though, which underneath uses a precompiled XML, so they never use the Resources instance.

Now you can work around this by using ViewPump like my lib does, or by using databinding like in your fork. Which is not really a good idea imho you would need to fetch every single string in your app using databinding if you want to go this way. And the databinding library is questionable in quite a few ways anyway...

Using a extra module does not reduce the complexity, as the complexity comes from the dependency on appcompat, which you need to use in your main module anyway...

The real solution would be to instead of working around appcompat to use the features it provides to solve the problem. E.g. by using a custom AppCompatViewInflater, maybe a custom AppCompatDelegateImpl depending on the subset of ViewPump features needed. I am working on something like this, but for now you need to rely on ViewPump or some workaround ;)

Hope this helps, I know it is a rather advanced android topic.

**Comment by ashu5398** [comment]
I got the point, I am working on it. I knew one product who has already worked on this problem and solved it efficiently. Just trying to implement something like that. Those guys are also using ViewPump and put an pre&post interceptor and override attributeSet in those interceptors. Let's see if I am able to do something like that.

**Comment by B3nedikt** [comment]
This is like my library "Reword" works, the readme of this library explains how to integrate it. But feel free to build something similar, depending on your apps architecture a custom solution may make sense.

**Comment by ashu5398** [comment]
My plan is to merge Restring and Reword so that End module should not be worried about multiple libraries and just integrate one. How's the idea?

**Comment by B3nedikt** [comment]
I don't know what you want to achieve by doing this. If you want to build a complete custom solution why not, but if you ever want to get back to my lib, that would make updating much more difficult. Also the problem is not Restring or Reword, it is the dependency of Reword & ViewPump on appcompat that makes stuff difficult. You always need to use the correct versions.
