### ISSUE TITLE
Overriding getDelegate() breaks styles attributes

### ISSUE THREAD

**Issue by hkarimka** [B3nedikt/restring#68]
Hello! I tried a new version 4.0.1 of ViewPump library.
Why is it neccesary to override `getDelegate()` and not just `getResources()` in BaseActivity in the new version 4.0.1 of ViewPump? 
It breaks my AlertDialog's title color, text colors and button colors.
These colors defined in my custom style using attributes `android:windowBackground`, `android:textColorPrimary` etc

**Comment by B3nedikt** [comment]
@hkarimka It is not strictly necessary, but does help a lot. The issue comes from appcompat 1.2.0 which makes "normal" context wrapping in attachBaseContext() more difficult, by essentially resetting everything set by the ContextWrapper. I think looking at the code of "AppCompatDelegateImpl.attachBaseContext2()" from the appcompat library explains the issue best ;)
Another issue with using a custom "LayoutInflater" like the old version of ViewPump is compatibility with some devices. Essentially "LayoutInflater" instances are created by the System, so these may be device specific, making all custom non device "LayoutInflater"s a bit hacky and in need of a lot of reflection.

That is the reason why I changed ViewPump to wrap the AppCompatDelegate. This essentially works around the issue by just using standard appcompat behavior. I think the issue you describe is connected to me simply not passing the context to the LayoutInflater...

This should be a small fix, ready by tonight. If not I think I revert everything for restring back to how it was before. This issue is obviously a deal breaker...

**Comment by B3nedikt** [comment]
@hkarimka Just updated ViewPump to version 4.0.2, you just need to increase the version and everything should work now :)
Feel free to open the ticket again, if you encounter similar problems though.

**Comment by hkarimka** [comment]
Thank you very much!
