### ISSUE TITLE
Migrate to Maven Central

### ISSUE THREAD

**Issue by zetbaitsu** [B3nedikt/restring#83]
JFrog just announced that they'll be shutting down JCenter:
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

Key dates are:

* February 28th: No more submissions will be accepted to Bintray, JCenter
* May 1st: Bintray, JCenter services will no longer be available

Hence `restring` should also be migrated to another maven repository like [Maven central](https://central.sonatype.org/).

**Comment by B3nedikt** [comment]
Hi, restring is already hosted on maven central since version 3.1, see: https://mvnrepository.com/artifact/dev.b3nedikt.restring/restring

I am using the maven sync from the bintray plugin for this though, which will need to be migrated for all my projects ;)
I am currently looking into alternatives for this plugin, maybe I will migrate the whole CI from travis to Github Actions, because there are already actions for directly deploying to maven central. What is your opinion on this?
