### ISSUE TITLE
attributes.getText() not work

### ISSUE THREAD

**Issue by TheMandalorianHub** [B3nedikt/restring#99]
the customer view to get the string resource is not work. just like:

`
class MineListItemView{
....

private fun initSetting() {
        val attributes = context.obtainStyledAttributes(attributeSet, R.styleable.MineListItemView)
        val size = attributes.indexCount
        for (i in 0..size) {
            when (val attr = attributes.getIndex(i)) {
                //<attr name="titleText" format="string"/>
                R.styleable.MineListItemView_titleText -> {
                   //the result is local  string.xml,not the set string resource
                    tv_title.text = attributes.getText(attr)
                }
}
}
`

**Comment by B3nedikt** [comment]
@TheMandalorianHub The issue here is that you use `obtainStyledAttributes(...)` directly, this method will only work with compiled XML files, so replacing them dynamically is not possible. You can normally work around this though, but I would need a bit more input here to give some advice ;)
If you want you can create a fork of this repository and modify the sample app so it reconstructs the issue. 
Does this help you?
